---
abstract: 'the missing piece in CPAN'
author:
  - 'Jozef Kutej <jkutej@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Universe-Galaxy
provides:
  Universe::Galaxy:
    file: lib/Universe/Galaxy.pm
    version: 0.03
  Universe::ObservableUniverse::Filament::SuperCluster::Cluster::Group::Galaxy::Arm::Bubble::InterstellarCloud::SolarSystem::Earth:
    file: lib/Universe/ObservableUniverse/Filament/SuperCluster/Cluster/Group/Galaxy/Arm/Bubble/InterstellarCloud/SolarSystem/Earth.pm
    version: 0.03
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
